### ISSUE TITLE
RA Offset should be calculated with cos(dec) term

### ISSUE THREAD

**Issue by wmwv** [lsst/dp0-2_lsst_io#14]
The RA Offset calculation in `tutorials_examples/portal-intermediate.rst` should have a cos(dec) term.  The line should be

```
((ra-67.4579634) * cos(decl * (3.14159/180))) * 3600
```

Does Firefly provide a `deg2rad` function or `dtor` equivalent constant?

**Comment by wmwv** [comment]
Both the text and the screenshot with the text should be updated.

**Comment by MelissaGraham** [comment]
Thanks, this is now seen and will be fixed: https://jira.lsstcorp.org/browse/PREOPS-1297
We will report back when issue is resolved.

**Comment by gpdf** [comment]
There is a `pi()` function available in Firefly's expressions already.  I'll take an action to look into providing a conversion function.

**Comment by Madejski** [comment]
Thanks for the heads-up, Michael!  It is all fixed now, and we added a little exercise for the learners to add error bars in the time-magnitude plot.  We merged the revised version to the main branch.  -Greg Madejski

**Comment by gpdf** [comment]
@wmwv As of yesterday, the data.lsst.cloud Portal supports the interactive use, in plot expressions, of `degrees()` and `radians()` functions.  The function names are taken from ADQL, for consistency.

Thus, you can now write `(ra-67.4579634) * cos(radians(decl)) * 3600` and the like.

**Comment by wmwv** [comment]
Thank you for the update to this secondary part of the bug report.  `radians` and `degrees` is much more civilized.

If you're following the ADQL standard, I presume that `degrees(x)` is implemented as a wrapper to provide a nice and readable way of spelling `(180/pi)*x` but the user still needs to know that the units of x are radians (and conversely for `radians`).  Is that correct?

**Comment by MelissaGraham** [comment]
A guess a question for @gpdf, is the addition of degrees() and radians() as plot expressions something to be added to the Portal documentation, e.g., at https://data.lsst.cloud/portal/app/onlinehelp/#plots.manipulating?

Maybe there should there be a separate ticket for that, or future questions, as this ticket is closed.
